pooltable/membership/urls.py
from django.urls import path
from . import views

app_name = 'membership'
urlpatterns = [
    path('', views.index, name='index'),
    #path('<int:member_id>/', views.detail, name='detail'),
    path('<int:member_id>/recharge/', views.recharge, name='recharge'),
    path('<int:member_id>/start_usage/', views.start_usage, name='start_usage'),
    path('<int:usage_id>/usage/', views.usage, name='usage'),
    path('<int:usage_id>/end_usage/', views.end_usage, name='end_usage'),
    path('<int:member_id>/delete/', views.delete_member, name='delete_member'),
    path('add_member/', views.add_member, name='add_member'),
    path('<int:member_id>/edit/', views.edit_member, name='edit_member'),
    path('memberlist/', views.member_list, name='member_list'),
    path('edit_member/<int:member_id>/', views.edit_member, name='edit_member'),
    path('delete_member/<int:member_id>/', views.delete_member, name='delete_member'),
    path('search/', views.search_member, name='search_member'),
    path('timer/', views.timer_view, name='timer'),
    path('pool_tables/', views.pool_table_view, name='pool_tables'),
    path('deposit/', views.deposit, name='deposit'),
    path('consume/', views.consume, name='consume'),
    path('get_table_status/', views.get_table_status, name='get_table_status'), 
    path('<int:member_id>/', views.member_detail, name='detail'),
]

pooltable/pooltable/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('membership.urls')),
    path("admin/", admin.site.urls),
    path('membership/', include('membership.urls')),
]

pooltable/membership/forms.py
from django import forms
from .models import Member

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ('name', 'phone', 'balance')
class DeleteMemberForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError('两次输入的密码不匹配')

pooltable/membership/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from .models import Member, Recharge, Usage
from .forms import MemberForm
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from .forms import MemberForm, DeleteMemberForm
from membership.models import Member, Transaction
import json
from django.http import HttpResponseBadRequest, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import PoolTable
from django.utils import timezone


from decimal import Decimal
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from membership.models import PoolTable, Member

from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import PoolTable, Member
from django.http import HttpResponseRedirect
from django.db.models import Q
from .models import Member, Consumption

def member_detail(request, member_id):
    member = Member.objects.get(id=member_id)
    usage_transactions = Consumption.objects.filter(member=member, type=Consumption.CONSUME).order_by('-timestamp')
    recharge_transactions = Consumption.objects.filter(member=member, type=Consumption.RECHARGE).order_by('-timestamp')
    context = {
        'member': member,
        'usage_transactions': usage_transactions,
        'recharge_transactions': recharge_transactions,
    }
    return render(request, 'membership/member_detail.html', context)
def search_member(request):
    search_query = request.GET.get('search', '')
    members = Member.objects.filter(Q(name__icontains=search_query) | Q(phone__icontains=search_query))
    return render(request, 'membership/membership_list.html', {'members': members})
@csrf_exempt
def deposit(request):
    if request.method == 'POST':
        member_id = request.POST.get('member_id')
        amount = Decimal(request.POST.get('amount'))
        if amount<=0:
            return JsonResponse({'success': False, 'message': 'Amount must be greater than zero'})
        member = get_object_or_404(Member, id=member_id)
        member.balance += amount
        member.save()
        consumption = Consumption.objects.create(
            member=member,
            amount=Decimal(amount),
            type=Consumption.RECHARGE,
        )
        return JsonResponse({'success': True})
@csrf_exempt
def consume(request):
    if request.method == 'POST':
        member_id = request.POST.get('member_id')
        amount = Decimal(request.POST.get('amount'))
        member = get_object_or_404(Member, id=member_id)
        if amount<=0:
            return JsonResponse({'success': False, 'message': 'Amount must be greater than zero'})
        if member.balance < amount:
            return JsonResponse({'success': False, 'message': 'Insufficient balance'})
        else:
            member.balance -= amount
            member.save()
            consumption = Consumption.objects.create(
                member=member,
                amount=Decimal(amount),
                type=Consumption.CONSUME,
            )
            return JsonResponse({'success': True})
def get_table_status(request):
    pool_tables = PoolTable.objects.all()
    context = {'pool_tables': pool_tables}
    return render(request, 'membership/table_status_partial.html', context)

def pool_table_view(request):
    # 获取所有的桌子和会员
    pool_tables = PoolTable.objects.all()
    members = Member.objects.all()

    # 初始化表格和会员变量
    table = None
    member = None

    # 检查表格选择表单是否提交
    if request.method == 'POST' and 'submit' in request.POST and 'table_id' in request.POST:
        table_id = request.POST.get('table_id')
        table = PoolTable.objects.get(id=table_id)

    # 检查会员选择表单是否提交
    if request.method == 'POST' and 'submit' in request.POST and 'member_id' in request.POST:
        member_id = request.POST.get('member_id')
        member = Member.objects.get(id=member_id)

    # 过滤使用中的桌子和已选的会员
    if table:
        pool_tables = pool_tables.filter(id=table.id)
    if member:
    # 过滤当前会员正在使用的桌子，或者没有任何会员使用的桌子
        pool_tables = pool_tables.filter(Q(current_member=member) | Q(current_member__isnull=True))


    # 计算消费金额
    money_to_pay = None
    if table and member:
        money_to_pay = table.get_usage_time() * member.rate_per_hour

    # 传递桌子、会员和消费金额给模板
    context = {
        'pool_tables': pool_tables,
        'members': members,
        'table': table,
        'member': member,
        'money_to_pay': money_to_pay,
    }

    return render(request, 'membership/pool_tables.html', context)

def timer_view(request):
    if request.method == 'POST':
        table_id = request.POST['table_id']
        pool_table = PoolTable.objects.get(id=table_id)
        if 'start' in request.POST:
            pool_table.start()
        elif 'pause' in request.POST:
            pool_table.pause()
        elif 'resume' in request.POST:
            pool_table.resume()
        elif 'stop' in request.POST:
            pool_table.stop()

        elif 'reset' in request.POST:
            pool_table.reset()
        return HttpResponseRedirect(request.path_info)

    pool_tables = PoolTable.objects.all()
    return render(request, 'membership/timer.html', {'pool_tables': pool_tables})



@csrf_exempt
def pool_table_start(request):
    if request.method == 'POST':
        pool_table_id = request.POST.get('pool_table_id')
        try:
            pool_table = PoolTable.objects.get(id=pool_table_id)
        except PoolTable.DoesNotExist:
            return HttpResponseBadRequest('Invalid pool table ID')

        if not pool_table.is_available:
            return HttpResponseBadRequest('Pool table is already in use')

        pool_table.start_timer()
        return JsonResponse({'status': 'success'})
    else:
        return HttpResponseBadRequest('Invalid request method')


@csrf_exempt
def pool_table_pause(request):
    if request.method == 'POST':
        pool_table_id = request.POST.get('pool_table_id')
        try:
            pool_table = PoolTable.objects.get(id=pool_table_id)
        except PoolTable.DoesNotExist:
            return HttpResponseBadRequest('Invalid pool table ID')

        if not pool_table.is_timer_running:
            return HttpResponseBadRequest('Pool table timer is not running')

        pool_table.pause_timer()
        return JsonResponse({'status': 'success'})
    else:
        return HttpResponseBadRequest('Invalid request method')


@csrf_exempt
def pool_table_resume(request):
    if request.method == 'POST':
        pool_table_id = request.POST.get('pool_table_id')
        try:
            pool_table = PoolTable.objects.get(id=pool_table_id)
        except PoolTable.DoesNotExist:
            return HttpResponseBadRequest('Invalid pool table ID')

        if not pool_table.is_timer_paused:
            return HttpResponseBadRequest('Pool table timer is not paused')

        pool_table.resume_timer()
        return JsonResponse({'status': 'success'})
    else:
        return HttpResponseBadRequest('Invalid request method')


@csrf_exempt
def pool_table_stop(request):
    if request.method == 'POST':
        pool_table_id = request.POST.get('pool_table_id')
        try:
            pool_table = PoolTable.objects.get(id=pool_table_id)
        except PoolTable.DoesNotExist:
            return HttpResponseBadRequest('Invalid pool table ID')

        if not pool_table.is_timer_running:
            return HttpResponseBadRequest('Pool table timer is not running')

        pool_table.stop_timer()
        return JsonResponse({'status': 'success', 'usage_time': pool_table.get_usage_time()})
    else:
        return HttpResponseBadRequest('Invalid request method')

def member_detail(request, member_id):
    member = get_object_or_404(Member, pk=member_id)
    #
    member = Member.objects.get(id=member_id)
    usage_transactions = Consumption.objects.filter(member=member, type=Consumption.CONSUME).order_by('-timestamp')
    recharge_transactions = Consumption.objects.filter(member=member, type=Consumption.RECHARGE).order_by('-timestamp')
    context = {
        'member': member,
        'usage_transactions': usage_transactions,
        'recharge_transactions': recharge_transactions,
    }
    return render(request, 'membership/detail.html', context)
    #
    transactions = Transaction.objects.filter(member=member)
    usage_transactions = []
    recharge_transactions = []
    for transaction in transactions:
        if transaction.amount < 0:
            usage_transactions.append(transaction)
        else:
            recharge_transactions.append(transaction)
    return render(request, 'membership/detail.html', {'member': member, 'usage_transactions': usage_transactions, 'recharge_transactions': recharge_transactions})

def member_list(request):
    members = Member.objects.all()
    return render(request, 'membership/index.html', {'members': members})

@login_required
def delete_member(request, member_id):
    member = get_object_or_404(Member, pk=member_id)

    if request.method == 'POST':
        form = DeleteMemberForm(request.POST)

        if form.is_valid():
            password = form.cleaned_data.get('password')
            user = authenticate(username=request.user.username, password=password)

            if user is not None:
                confirm_password = form.cleaned_data.get('confirm_password')

                if password == confirm_password:
                    member.delete()
                    return HttpResponseRedirect('/membership/')
                else:
                    form.add_error('confirm_password', '两次输入的密码不匹配')
    else:
        form = DeleteMemberForm()
        
    return render(request, 'membership/delete_member.html', {'member': member, 'form': form})

@login_required(login_url='/admin/login/')
def index(request):

pooltable/membership/templates/membership/add_member.html
{% extends 'base.html' %}

{% block content %}
  <h2>添加新会员</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">提交</button>
  </form>
{% endblock %}

pooltable/membership/templates/membership/delete_member.html
{% extends 'base.html' %}

{% block content %}
  <h1>删除会员 {{ member }}</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-danger">确认删除</button>
    <a href="{% url 'membership:member_list' %}" class="btn btn-default">取消</a>
  </form>

{% endblock %}

pooltable/membership/templates/membership/detail.html
<nav>
    <ul>
        <li><a href="{% url 'admin:index' %}">后台管理</a></li>
        <li><a href="{% url 'membership:add_member' %}">添加会员</a></li>
        <li><a href="{% url 'membership:index' %}">会员列表</a></li>
        <li><a href="{% url 'membership:timer' %}">使用计时器</a></li>
      <!-- 其他导航链接 -->
    </ul>
</nav>
<h2>消费记录</h2>
{% for transaction in usage_transactions %}
    <p>{{ transaction.timestamp|date:"Y-m-d H:i:s" }} 消费 {{ transaction.amount }}</p>
{% empty %}
    <p>没找到消费记录.</p>
{% endfor %}

<h2>充值记录</h2>
{% for transaction in recharge_transactions %}
    <p>{{ transaction.timestamp|date:"Y-m-d H:i:s" }} 充值 {{ transaction.amount }}</p>
{% empty %}
    <p>没找到充值记录.</p>
{% endfor %}

pooltable/membership/templates/membership/edit_member.html
{% extends 'base.html' %}

{% block title %}编辑会员信息{% endblock %}

{% block content %}
  <h2>编辑会员信息</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">保存</button>
  </form>
  <p><a href="{% url 'membership:index' %}">返回列表</a></p>
{% endblock %}

pooltable/membership/templates/membership/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>会员管理系统</title>

    
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'admin:index' %}">后台管理</a></li>
            <li><a href="{% url 'membership:add_member' %}">添加会员</a></li>
            <li><a href="{% url 'membership:index' %}">会员列表</a></li>
            <li><a href="{% url 'membership:timer' %}">使用计时器</a></li>
          <!-- 其他导航链接 -->
        </ul>
      </nav>
    <form action="{% url 'membership:search_member' %}" method="get">
        <label for="search">搜索会员（姓名或手机号）：</label>
        <input type="text" name="search" required>
        <button type="submit">搜索</button>
    </form>
    <button id="toggle-membership-list">隐藏会员列表</button>
    <div id="membership-list-wrapper">
    <h1>会员列表</h1>
        <ul>
            {% include 'membership/members_pure.html' %}
        </ul>
    <hr>
    </div>

</body>
<script>
    const toggleButton = document.getElementById('toggle-membership-list');
    const membershipList = document.getElementById('membership-list-wrapper');

    toggleButton.addEventListener('click', function() {
        if (membershipList.style.display === 'none') {
            membershipList.style.display = 'block';
            toggleButton.textContent = '隐藏会员列表';
        } else {
            membershipList.style.display = 'none';
            toggleButton.textContent = '显示会员列表';
        }
    });
</script>
</html>

pooltable/membership/templates/membership/members_pure.html
{% for member in members %}
<li>
    <a href="{% url 'membership:detail' member.id %}">{{ member.name }}</a> 
    (余额：{{ member.balance }})
</li>
<tr>
    <td>{{ member.name }}</td>
    <td>{{ member.phone }}</td>
    <td>{{ member.balance }}</td>
    <td><a href="{% url 'membership:edit_member' member.pk %}">编辑</a> | <a href="{% url 'membership:delete_member' member.pk %}">删除</a></td>
</tr>
{% empty %}
<li>没有会员</li>
{% endfor %}

pooltable/membership/templates/membership/membership_list.html
<!--
{% for member in members %}
<li>
    <a href="{% url 'membership:detail' member.id %}">{{ member.name }}</a> 
    (余额：{{ member.balance }})
</li>
<tr>
    <td>{{ member.name }}</td>
    <td>{{ member.phone }}</td>
    <td>{{ member.balance }}</td>
    <td><a href="{% url 'membership:edit_member' member.pk %}">编辑</a> | <a href="{% url 'membership:delete_member' member.pk %}">删除</a></td>
</tr>
{% empty %}
<li>没有会员</li>
{% endfor %}
-->
<nav>
    <ul>
        <li><a href="{% url 'admin:index' %}">后台管理</a></li>
        <li><a href="{% url 'membership:add_member' %}">添加会员</a></li>
        <li><a href="{% url 'membership:index' %}">会员列表</a></li>
        <li><a href="{% url 'membership:timer' %}">使用计时器</a></li>
      <!-- 其他导航链接 -->
    </ul>
</nav>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
    $('form').submit(function(event) {
        event.preventDefault(); // prevent the form from submitting normally
        var form = $(this);
        var action = form.find('button').data('action');
        var url = form.attr('action');
        var data = form.serialize();
        $.ajax({
            url: url,
            data: data,
            type: 'post',
            dataType: 'json',
            success: function(response) {
                if (response.success) {
                    // display success alert
                    if (action == 'consume')
                        alert('消费成功');
                    if (action == 'deposit')
                        alert('充值成功');
                    window.location.reload();
                    // clear the amount input field
                    form.find('input[name="amount"]').val('');
                    
                    // update the balance or consumption history section
                    // based on the action
                    if (action == 'consume') {
                        // update consumption history section
                        // with the new entry returned in the response
                        var entry = response.entry;
                        var row = $('<tr><td>' + entry.timestamp + '</td><td>' + entry.amount + '</td></tr>');
                        $('#consumption-history tbody').prepend(row);
                        
                        // update the balance section with the new balance
                        var balance = response.balance;
                        $('#balance').text(balance);
                    } else if (action == 'deposit') {
                        // update the balance section with the new balance
                        var balance = response.balance;
                        $('#balance').text(balance);
                    }
                } else {
                    // display error alert
                    if (action == 'consume')
                        alert('消费失败'+response.message);
                    if (action == 'deposit')
                        alert('充值失败'+response.message);  
                }
            },
            error: function(xhr, errmsg, err) {
                // display error alert
                alert('Error');
            }
        });
    });
});
</script>
{% for member in members %}
    <form method="POST" action="{% url 'membership:consume' %}">
        {% csrf_token %}
        <input type="hidden" name="member_id" value="{{ member.id }}">
        <input type="text" name="amount" placeholder="请输入消费金额">
        <button data-action="consume" type="submit">确认消费</button>
    </form>
    <form method="POST" action="{% url 'membership:deposit' %}">
        {% csrf_token %}
        <input type="hidden" name="member_id" value="{{ member.id }}">
        <input type="text" name="amount" placeholder="请输入充值金额">
        <button data-action="deposit"  type="submit">确认充值</button>
    </form>
    

    
    <tr>
        <a href="{% url 'membership:detail' member.id %}">{{ member.name }}</a>
        <!--<td>{{ member.phone }}</td>-->
        <td>{{ member.balance }}</td>
        <td>
            <a href="{% url 'membership:edit_member' member.pk %}">编辑</a> | 
            <a href="{% url 'membership:delete_member' member.pk %}">删除</a>
        </td>
    </tr>
{% empty %}
    <li>没有符合条件的会员</li>
{% endfor %}

pooltable/membership/templates/membership/pool_tables.html
{% extends "base.html" %}

{% block content %}
  <h2>台球桌计时器</h2>
  
  <!-- 表格选择表单 -->
  <form method="post" id="table-form">
    {% csrf_token %}
    <label for="table_id">桌子ID:</label>
    <select id="table_id" name="table_id" required autocomplete="off">
      {% for table in pool_tables %}
        <option value="{{ table.id }}">{{ table.name }}</option>
      {% endfor %}
    </select>
    <button type="submit" name="submit">选择</button>
  </form>
  
  <!-- 会员选择表单 -->
  <form method="post" id="member-form">
    {% csrf_token %}
    <label for="member_id">会员ID（可选）:</label>
    <select id="member_id" name="member_id" autocomplete="off">
      {% for member in members %}
        <option value="{{ member.id }}">{{ member.name }}</option>
      {% endfor %}
    </select>
    <button type="submit" name="submit">选择</button>
  </form>
  
  {% if table %}
    <h3>桌子状态</h3>
    <ul>
      <li>桌子名：{{ table.name }}，是否可用：{{ table.is_available }}，当前会员：{{ table.current_member }}，开始时间：{{ table.start_time }}，结束时间：{{ table.end_time }}，暂停时间：{{ table.paused_time }}，使用时间：{{ table.get_usage_time }}。</li>
      {% if member %}
        <li>会员：{{ member.name }}，费率：{{ member.rate_per_hour }}/小时</li>
        {% if money_to_pay %}
          <li>消费金额：{{ money_to_pay }}</li>
        {% endif %}
      {% endif %}
      {% if table.is_available %}
        <form method="post">
          {% csrf_token %}
          <button type="submit" name="start">开始计时</button>
        </form>
      {% else %}
        <form method="post">
          {% csrf_token %}
          <button type="submit" name="pause">暂停计时</button>
          <button type="submit" name="resume">恢复计时</button>
          <button type="submit" name="stop">停止计时</button>
          <button type="submit" name="reset">重置计时器</button>
        </form>
      {% endif %}
    </ul>
  {% else %}
    <p>请选择一张桌子。</p>
  {% endif %}

{% endblock %}

pooltable/membership/templates/membership/table_status_partial.html
<ul id="table_status">
    {% for table in pool_tables %}
    <li>桌子名：{{ table.name }}，是否可用：{{ table.is_available }}，当前会员：{{ table.current_member }}，开始时间：{{ table.start_time }}，结束时间：{{ table.end_time }}，暂停时间：{{ table.paused_time }}。</li>
      <p>使用时间：{{ table.get_elapsed_time }}</p>
      <p>消费金额：{{ table.get_cost }}</p>
    {% empty %}
      <li>无桌子数据。</li>
    {% endfor %}
  </ul>
  

pooltable/membership/templates/membership/timer.html
{% extends "base.html" %}

  
{% block content %}

  <h2>台球桌计时器</h2>
  <form method="post">
    {% csrf_token %}


    <label for="table_id">桌子ID:</label>
    <select id="table_id" name="table_id" required autocomplete="off">
        {% for table in pool_tables %}
          <option value="{{ table.id }}">{{ table.name }}</option>
        {% endfor %}
      </select>
    <br>
    <button type="submit" name="start" onclick="confirmAction('开始计时！桌号：' + document.getElementById('table_id').value, '您确定要开始计时吗？', 'start', event)">开始计时</button>
    <button type="submit" name="pause" onclick="confirmAction('暂停计时！桌号：' + document.getElementById('table_id').value, '您确定要暂停计时吗？', 'pause', event)">暂停计时</button>
    <button type="submit" name="resume" onclick="confirmAction('恢复计时！桌号：' + document.getElementById('table_id').value, '您确定要恢复计时吗？', 'resume', event)">恢复计时</button>
    <button type="submit" name="stop" onclick="confirmAction('停止计时！桌号：' + document.getElementById('table_id').value, '您确定要停止计时吗？', 'stop', event)">停止计时</button>
    <button type="submit" name="reset" onclick="confirmAction('重置计时器！桌号：' + document.getElementById('table_id').value, '您确定要重置计时器吗？', 'reset', event)">重置计时器</button>
    
    <script>
    function confirmAction(message, confirmation, action, event) {
        if (confirm(`您选择了操作${action}，${message}。是否确认执行该操作？`)) {
            // 如果用户确认执行操作，则不需要中止表单提交
        } else {
            // 如果用户取消操作，则需要中止表单提交
            event.preventDefault();
        }
    }
    </script>
    
    
    


  </form>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>function load_table_status() {
    $.ajax({
      url: "/membership/get_table_status/",
      type: "GET",
      success: function(data) {
        $("#table_status").html(data);
      },
      error: function(xhr, errmsg, err) {
        console.error("Error: " + xhr.status + ": " + errmsg);
      },
    });
  }
  
  // 定期更新桌子状态
  setInterval(load_table_status, 500); // 每5秒刷新一次
  </script>
  <h3>桌子状态</h3>
  {% include 'membership/table_status_partial.html' %}
  <!--<ul id="table_status"> 
    {% for table in pool_tables %}
    <li>桌子名：{{ table.name }}，是否可用：{{ table.is_available }}，当前会员：{{ table.current_member }}，开始时间：{{ table.start_time }}，结束时间：{{ table.end_time }}，暂停时间：{{ table.paused_time }}。</li>
      <p >使用时间：{{ table.get_elapsed_time }}</p>
      <p >消费金额：{{ table.get_cost }}</p>
    {% empty %}
      <li>无桌子数据。</li>
    {% endfor %}
  </ul>-->  

{% endblock %}